### ISSUE TITLE
warnings when run m1 on Windows

### ISSUE THREAD

**Issue by cmlegault** [timjmiller/wham#17]
When run m1 from example scripts on Windows got 50+ warnings:
In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
Tim noted this did not happen on linux

**Comment by brianstock-NOAA** [comment]
Hi Chris,

We've debugged a few issues that were either Windows-specific or due to old package versions: https://github.com/timjmiller/wham/issues/28, https://github.com/timjmiller/wham/issues/27, https://github.com/timjmiller/wham/issues/25. Chuck was able to get everything working using R 3.6 as well. Can you update TMB and WHAM, then see if you're still getting this warning? 

```
devtools::install_github("kaskr/adcomp/TMB", dependencies=TRUE)
devtools::install_github("timjmiller/wham", dependencies=TRUE)
```

It could also be worth updating the other packages WHAM uses. See the [DESCRIPTION file](https://github.com/timjmiller/wham/blob/master/DESCRIPTION).

You can now run all 6 examples with (takes about an hour):
```
# setwd("choose/where/to/save/output") # otherwise in working directory
library(wham)
wham.dir <- find.package("wham")
source(file.path(wham.dir, "example_scripts", "run_all_examples.R"))
```

**Comment by cmlegault** [comment]
Hi Brian,

I was able to install and run wham on my Windows machine for the Index Based Methods Working Group. Your fixes have solved this problem. I haven't tried all the examples yet, but will eventually. I don't expect any problems. 

Thanks,
Chris
