### ISSUE TITLE
'pivot_longer' is not an exported object from 'namespace:tidyr'

### ISSUE THREAD

**Issue by Charles-Adams-NOAA** [timjmiller/wham#27]
Got the following error while trying to output the plots from example 1 as a PDF:

> plot_wham_output(mod=m4_proj, out.type='pdf')
Generating plot files... Please wait ~30 seconds...
Error: 'pivot_longer' is not an exported object from 'namespace:tidyr'

**Comment by brianstock-NOAA** [comment]
That's weird because `pivot_longer` is an exported function from `tidyr`. I wonder if it's because you have an old version of `tidyr` installed, and I've used a newer version but only specified that an older version needs to be installed in `wham`'s `DESCRIPTION` file... What version of R and `tidyr` are you using?

Run
`packageVersion("tidyr")`
`version[['version.string']]`

Try 
`update.packages(ask=F)`

**Comment by Charles-Adams-NOAA** [comment]
PDF files successfully created after updating to tidyr version 1.1.2
