### ISSUE TITLE
How are selectivity models and parameters defined in the ASAP3 file?

### ISSUE THREAD

**Issue by brianstock-NOAA** [timjmiller/wham#29]
Dear Tim and Brian,

Most of the slots in the input file are well described but others, for example, "Selectivity block" are not easy to follow because I do not know what the numbers mean. Do you have a manual or an input file (.txt) describing each slot?

**Comment by brianstock-NOAA** [comment]
Sorry - we haven't explained the input file structure in detail because (for now) we assumed WHAM users would have an ASAP3 data file already. [Section 3 in Ex 4](https://timjmiller.github.io/wham/articles/ex4_selectivity.html#setup-and-run-models) shows how the selectivity blocks are defined in the ASAP3 file. 

Each selectivity block has one of these options: 1 = age-specific, 2 = logistic, 3 = double-logistic, 4 = logistic (declining).

Each block has 4 columns and (# ages + 6) rows:
  - Column 1: initial parameter value
  - Column 2: estimation phase, used in ADMB but not TMB/WHAM. Any negative # here will tell WHAM to fix (not estimate) the parameter.
  - Columns 3-4: I actually don't know what these do but am guessing they are lower and upper bounds for the selectivity parameters. I would keep them at 0 in col 3 and 1 in col 4 (selectivity between 0 and 1).

The number of rows is the number of ages (n.ages) + 6.
  - Rows 1-n.ages: selectivity for each age (used if "age-specific" selectivity is specified, option 1)
  - The next 2 rows are the logistic selectivity parameters (option 2)
  - The last 4 rows are used for the double-logistic (option 3)

Rows pertaining to options that are not used are ignored. In other words, the example 4 file uses logistic selectivity (option 2). There are 6 ages in the assessment (so 12 rows in the selectivity block parameter matrix). Rows 7 and 8 specify the logistic selectivity parameters and are the only rows used.

Thank you for the interest and feedback - we could certainly improve this part of the documentation.

**Comment by brianstock** [comment]
Improving documentation for the selectivity parameter setup in asap .dat files, since I am back on this page looking for it again...

Col 1: initial par value
Col 2: estimation phase (not used in TMB/WHAM except if it is negative then WHAM fixes it at the initial value)
Col 3: lambda (1 = add penalty, 0 = no penalty, freely estimated)
Col 4: CV (strength of penalty, sig2 = log(CV*CV + 1), so lower value = tighter distribution = estimate kept closer to initial, see ASAP3 tech manual). Ex CV of 0.5 = sig2 of 0.22, CV of 0.25 = sig2 of 0.06.
