### ISSUE TITLE
Aggregate index

### ISSUE THREAD

**Issue by ejosymart** [timjmiller/wham#30]
Is it possible to run the model using two aggregate indices (CPUE and Echoabundance, one value per year, no ages)? Or how can I prepare my input.dat or modify it based on your example1 (Ex 1: The basics).

Thanks.

**Comment by brianstock-NOAA** [comment]
Yes, you can use multiple indices. I'm sorry, we have not put much effort (yet) into describing the ASAP file structure because most applications of WHAM at the NEFSC already have an existing ASAP file.

The [data file for ex1](https://github.com/timjmiller/wham/blob/master/inst/extdata/ex1_SNEMAYT.dat) has 2 indices, and the [data file for ex2](https://github.com/timjmiller/wham/blob/master/inst/extdata/ex2_SNEMAYT.dat) has 5 indices.
