### ISSUE TITLE
Error in install with vignette

### ISSUE THREAD

**Issue by timjmiller** [timjmiller/wham#6]
This happens when I try to install with the vignette:

####################################################
devtools::install_github("timjmiller/wham", dependencies=TRUE, build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo timjmiller/wham@master
✔  checking for file ‘/tmp/Rtmp4hAsEF/remotes5f194b57b497/timjmiller-wham-4160778/DESCRIPTION’ ...
─  preparing ‘wham’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (1m 19.3s)
   --- re-building ‘SNEMA_yellowtail_flounder.Rmd’ using rmarkdown
   Quitting from lines 18-33 (SNEMA_yellowtail_flounder.Rmd) 
   Error: processing vignette 'SNEMA_yellowtail_flounder.Rmd' failed with diagnostics:
   cannot change working directory
   --- failed re-building ‘SNEMA_yellowtail_flounder.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘SNEMA_yellowtail_flounder.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
######################################################

Looking at the offending file (SNEMA_yellowtail_flounder.Rmd), I see on line 15 that a file on the local machine is being referenced.

**Comment by brianstock** [comment]
Thanks for catching that! Should be fixed now if you want to try again.

Also - I've found that the html looks better if I install using RStudio (instead of the terminal). Seems like this is because when you install from RStudio it uses the included version of pandoc (see [here](https://stackoverflow.com/questions/50394988/rmarkdown-theme-not-applied-in-vignette-using-r-cmd-build)).
